# Generated by Django 5.1.4 on 2024-12-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите краткое описание урока",
                max_length=800,
                null=True,
                verbose_name="Описание курса",
            ),
        ),
    ]
