# Generated by Django 5.1.4 on 2025-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления"),
        ),
    ]
